### ISSUE TITLE
Refresh server data

### ISSUE THREAD

**Issue by polskiemedia** [wmi-students/wmi-timetable-android#26]
Trzeba by było zrobić, żeby po uruchimieniu apki, on w tle zaciągał dane z serwera, bo teraz jak on zaciągnie, to już aż do reset ma swoją wersję, jakby były zmiany na planie to można przeoczyć

**Comment by wubli** [comment]
Przy każdym uruchomieniu zaciągać, jakiś przedział czasowy?

**Comment by polskiemedia** [comment]
Trzeba dodac web service który podaje datę  ostatniej aktualizacji danych. Ta data powinna znajdować się również w tych danych ktore pobieramy teraz.  Aplikacja powinna zapisać  sobie tą date po pobraniu danych. Jeśli mamy dane czyli np w drugim uruchomieniu aplikacji to uderzamy do nowego resta po uruchomieniu w tle. Sprawdzamy czy nie ma nowszych danych. Jesli są to ladujemy je albo dajemy znać uzytkownikowi z prośbą o odświeżenie.

**Comment by wubli** [comment]
W JSON nie są zawsze najnowsze dane? 043d81b zapisuje datę ostatniego pobrania. 
W 6175fee ustawienie: jeśli dane starsze niż 2 dni to pobiera w tle.
